<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Enable_Target_CopyDebugJsonToSettingsOutput>true</Enable_Target_CopyDebugJsonToSettingsOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Autofac" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Fxc" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZYC.Framework.Abstractions\ZYC.Framework.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Core\ZYC.Framework.Core.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.Aspire.Abstractions\ZYC.Framework.Modules.Aspire.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.Language.Abstractions\ZYC.Framework.Modules.Language.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.Mock.Abstractions\ZYC.Framework.Modules.Mock.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.Secrets.Abstractions\ZYC.Framework.Modules.Secrets.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.TaskManager.Abstractions\ZYC.Framework.Modules.TaskManager.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.Modules.Update.Abstractions\ZYC.Framework.Modules.Update.Abstractions.csproj" />
    <ProjectReference Include="..\ZYC.Framework.WebView2\ZYC.Framework.WebView2.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Shaders\Crt.ps" />
    <Resource Include="Shaders\Crt.ps" />
  </ItemGroup>
  <Target BeforeTargets="Build" Name="BuildShader" Condition="!Exists('./Shaders/Crt.ps')">
    <Exec Command="$(NuGetPackageRoot)ZYC.CoreToolkit.Extensions.Fxc\$(V_ZYC_CoreToolkit_Extensions_Fxc)\build\x64\fxc.exe /T ps_3_0 /E main /Fo Shaders/Crt.ps Shaders/Crt.fx" />
  </Target>
</Project>