<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Enable_Target_CopyDebugJsonToSettingsOutput>true</Enable_Target_CopyDebugJsonToSettingsOutput>
  </PropertyGroup>
  <PropertyGroup>
    <IgnoreFromPublish>true</IgnoreFromPublish>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZYC.Framework.Modules.__PROJECT_NAME__.Abstractions\ZYC.Framework.Modules.__PROJECT_NAME__.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ZYC.Framework.Core">
      <HintPath>$(OutputPath)ZYC.Framework.Core.dll</HintPath>
    </Reference>
    <Reference Include="ZYC.Framework.Abstractions">
      <HintPath>$(OutputPath)ZYC.Framework.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Autofac" />
  </ItemGroup>
</Project>
