<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Autofac" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" />
    <PackageReference Include="ZYC.CoreToolkit" />
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="Emoji.Wpf" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="SharpVectors" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZYC.Framework.Abstractions\ZYC.Framework.Abstractions.csproj" />
  </ItemGroup>
  <Target BeforeTargets="PrepareForBuild" Name="BuildShader" Condition="!Exists('./Shaders/GrayScale.ps')">
    <Exec Command="$(NuGetPackageRoot)ZYC.CoreToolkit.Extensions.Fxc\$(V_ZYC_CoreToolkit_Extensions_Fxc)\build\x64\fxc.exe /T ps_3_0 /E main /Fo Shaders/GrayScale.ps Shaders/GrayScale.fx" />
  </Target>
</Project>