<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>


  <PropertyGroup>
    <EnableFody>true</EnableFody>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="ZYC.CoreToolkit" />
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Autofac" />
    <PackageReference Include="ZYC.CoreToolkit.Extensions.Settings" />
  </ItemGroup>




</Project>
