<Project>

  <Import Project="$(MSBuildThisFileDirectory)nuget.props" />

  <Import Project="$(MSBuildThisFileDirectory)version.props" Condition="Exists('$(MSBuildThisFileDirectory)version.props')" />

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU5104</NoWarn>
    <NoWarn>$(NoWarn);MSB3270</NoWarn>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
    <NoWarn>$(NoWarn);CSS102</NoWarn>
    <NoWarn>$(NoWarn);CS8620</NoWarn>
    <NoWarn>$(NoWarn);NETSDK1057</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <EnableWpf>true</EnableWpf>
  </PropertyGroup>

  <PropertyGroup Condition="'$(EnableWpf)' == 'true'">
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(EnableWpf)' != 'true' or $(MSBuildProjectName.EndsWith('.Abstractions'))">
    <TargetFramework>net10.0</TargetFramework>
    <UseWPF>false</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Abstractions'))">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath>$(MSBuildThisFileDirectory)_bin/$(Version)/</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>


  <PropertyGroup>
    <SatelliteResourceLanguages>_</SatelliteResourceLanguages>
    <ResolveAssemblyReferencesFindRelatedSatellites>false</ResolveAssemblyReferencesFindRelatedSatellites>
  </PropertyGroup>


  <PropertyGroup>
    <IgnoreFromPublish>false</IgnoreFromPublish>
  </PropertyGroup>

  <PropertyGroup>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>


  <PropertyGroup>
    <RazorLangVersion>8.0</RazorLangVersion>
    <GenerateScopedCss>false</GenerateScopedCss>
  </PropertyGroup>



  <PropertyGroup>
    <EnableFody Condition="'$(EnableFody)' == ''">false</EnableFody>
  </PropertyGroup>

  <ItemGroup Condition="'$(EnableFody)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)FodyWeavers.xml"
          Link="FodyWeavers.xml" />
    <PackageReference Include="PropertyChanged.Fody" />
  </ItemGroup>




  <PropertyGroup>
    <Enable_Target_CopyJsonToSettingsOutput>false</Enable_Target_CopyJsonToSettingsOutput>
    <Enable_Target_CopyDebugJsonToSettingsOutput>false</Enable_Target_CopyDebugJsonToSettingsOutput>
    <SettingsJsonOutputDir>$([System.IO.Path]::GetFullPath('$(OutputPath)..\'))</SettingsJsonOutputDir>
  </PropertyGroup>

  <ItemGroup>
    <JsonFiles Include="*.json" />
    <!--<JsonFiles Include="**\*.json" />-->
  </ItemGroup>


  <Target Name="CopyJsonToSettingsOutput"
          AfterTargets="Build"
          Condition="'$(Enable_Target_CopyJsonToSettingsOutput)' == 'true'">
    <Copy SourceFiles="@(JsonFiles)"
          DestinationFiles="@(JsonFiles->'$(SettingsJsonOutputDir)\%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyDebugJsonToSettingsOutput"
          AfterTargets="Build"
          Condition="'$(Configuration)' == 'Debug' and '$(Enable_Target_CopyDebugJsonToSettingsOutput)' == 'true'">
    <Copy SourceFiles="@(JsonFiles)"
          DestinationFiles="@(JsonFiles->'$(SettingsJsonOutputDir)\%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>


  <ItemGroup>
    <None Remove="**\*.ps" />
    <Resource Include="**\*.ps" />
  </ItemGroup>

</Project>