<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IgnoreFromPublish>true</IgnoreFromPublish>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZYC.Framework.Abstractions\ZYC.Framework.Abstractions.csproj" />
  </ItemGroup>
  <!--<ItemGroup>
    <Reference Include="ZYC.Framework.Abstractions">
      <HintPath>$(OutputPath)ZYC.Framework.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>-->
</Project>