name: Publish NuGet Package
on:
  workflow_dispatch:

jobs:
  publish:
    name: Push to NuGet.org
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
# //TODO-zyc Enable_GENERATE_DOC
      - run: |
          dotnet run --project src/ZYC.Framework.Build.NuGet/ZYC.Framework.Build.NuGet.csproj -c Release -p:Enable_GENERATE_DOC=false -p:Enable_PUBLISH_NUGET_ORG=true
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}