name: Publish Setup Release
on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag(v1.x.x) to publish the setup asset to
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Push Setup to Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          dotnet run --project src/ZYC.Framework.Build.InnoSetup/ZYC.Framework.Build.InnoSetup.csproj -c Release -p:Enable_GENERATE_DOC=false -p:Enable_PUBLISH_GITHUB_RELEASE=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
